config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recruitments, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
    resources :recruitment_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
     resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
  end
  post 'users/withdrawal/:user_id', to: 'users#withdrawal', as: 'withdrawal'
  root "homes#top"
  get "home/about"=>"homes#about"
  get '/homes/guest_login', to: 'homes#guest_login'
  get "search" => "searches#search"

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recruitment_comment.rb
class RecruitmentComment < ApplicationRecord
    belongs_to :user
    belongs_to :recruitment
    
    validates :comment, presence: true
end

app/controllers/recruitment_comments_controller.rb
class RecruitmentCommentsController < ApplicationController
  def create
    recruitment = Recruitment.find(params[:recruitment_id])
    comment = current_user.recruitment_comments.new(recruitment_comment_params)
    comment.recruitment_id = recruitment.id
    if comment.save
      redirect_to request.referer, notice: "コメントを投稿しました"
    else
      flash[:alert] = "コメントの投稿に失敗しました"
      redirect_to request.referer
    end
  end

  def destroy
    RecruitmentComment.find_by(id: params[:id], recruitment_id: params[:recruitment_id]).destroy
    redirect_to request.referer
  end

  private
  def recruitment_comment_params
    params.require(:recruitment_comment).permit(:comment)
  end
end

app/helpers/recruitment_comments_helper.rb
module RecruitmentCommentsHelper
end

app/helpers/recruitmentcomments_helper.rb
module RecruitmentcommentsHelper
end

app/views/recruitment_comments/_form.html.erb
<%= form_with(model:[recruitment, recruitment_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信" %>
<% end %>

app/views/recruitment_comments/_index.html.erb
<table class = "w-100">
  <tbody>
      <% recruitment.recruitment_comments.each do |recruitment_comment| %>
      <tr class = "w-100">

        <td class = "col-100px">
          <%= link_to user_path(recruitment_comment.user) do %>
            <%= image_tag recruitment_comment.user.get_profile_image, size: "50x50" %><br>
            <span class = "font-small"><%= recruitment_comment.user.name %></span>
          <% end %>
        </td>
        <td><div class = "hukidasi"><%= recruitment_comment.comment %><br>
          <small class="text-bloack-50"><%= recruitment_comment.created_at.in_time_zone("Tokyo").strftime("%Y/%m/%d %H:%M") %></small>
          </div></td>
        <td class = "col-60px">
          <% if (recruitment_comment.user == current_user || current_user.is_admin?) %>
            <%= link_to "削除", recruitment_recruitment_comment_path(recruitment, recruitment_comment), method: :delete, class: "btn btn-danger pull-right btn-sm", data: { confirm: "【確認】コメントを削除してもよろしいですか？" } %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/recruitment_comments/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/recruitment_comments/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @recruitment %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー詳細</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">新しい募集</h2>
      <%= render 'form', recruitment: @recruitment %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>募集</h2>
      <%= render 'index', recruitments: @recruitments%>
    </div>
  </div>
</div>

app/views/recruitment_comments/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー名</h2>
      <%= render 'users/info', user: @recruitment.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', recruitment: Recruitment.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
      <table class='table'>
        <tr>
          <td>
            <%= link_to(@recruitment.user) do %>
              <%= image_tag @recruitment.user.get_profile_image, size:"100x100" %><br>
              <%= @recruitment.user.name %>
            <% end %>
          </td>
          <td><%= link_to @recruitment.title, @recruitment %></td>
          <td><%= @recruitment.body %></td>
          <td><%= render "favorites/btn", recruitment: @recruitment %></td>
          <td>コメント数: <%= @recruitment.recruitment_comments.count %></td>
          <% if @recruitment.user == current_user %>
            <td><%= link_to 'Edit', edit_recruitment_path(@recruitment), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @recruitment, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}" %></td>
          <% end %>
        </tr>
      </table>

      <%= render "recruitment_comments/index", recruitment: @recruitment %>
      <%= render "recruitment_comments/form", recruitment: @recruitment, recruitment_comment: @recruitment_comment %>
    </div>
  </div>
</div>