config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recruitments, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
    resources :recruitment_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
     resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
  end
  post 'users/withdrawal/:user_id', to: 'users#withdrawal', as: 'withdrawal'
  root "homes#top"
  get "home/about"=>"homes#about"
  get '/homes/guest_login', to: 'homes#guest_login'
  get "search" => "searches#search"

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
 before_action :authenticate_user!
  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user)
  end

  def followings
    @user = User.find(params[:user_id])
		@users = @user.followings
  end

  def followers
    @user = User.find(params[:user_id])
		@users = @user.followers
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_btn.html.erb
<% if current_user != user%>
  <% if current_user.following?(user) %>
    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-danger pull-right btn-sm" %>
  <% else %>
    <%= link_to "フォローをする", user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-primary pull-right btn-sm" %>
  <% end %>
<% end %>

app/views/relationships/create.js.erb
$("#relationships-btn-<%=@user.id %>").html("<%= escape_javascript(render partial: 'relationships/btn', locals: {user: @user}) %>");

app/views/relationships/destroy.js.erb
$("#relationships-btn-<%=@user.id %>").html("<%= escape_javascript(render partial: 'relationships/btn', locals: {user: @user}) %>");

app/views/relationships/followers.html.erb
<h2><%= @user.name %>さんのフォロワー 一覧</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーは現在いません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2><%= @user.name %>さんのフォロー中 一覧</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーは現在いません</p>
<% end %>