config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recruitments, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
    resources :recruitment_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
     resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
  end
  post 'users/withdrawal/:user_id', to: 'users#withdrawal', as: 'withdrawal'
  root "homes#top"
  get "home/about"=>"homes#about"
  get '/homes/guest_login', to: 'homes#guest_login'
  get "search" => "searches#search"

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recruitments
  has_many :recruitment_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_tags
  has_many :tags, through: :user_tags

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  #validates :introduction, length: { maximum: 50 }


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.png'
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def is_guest?
    email == "guest@example.com"
  end

  def active_for_authentication? # アカウント凍結のログイン分岐
    super && (is_withdrawal == false)
  end

  def inactive_message # アカウント凍結時のエラーメッセージ
    !is_withdrawal ? super : :locked
  end

  def self.looks(search, word)
    if search == "perfect_match"
       User.where("name LIKE ?", "#{word}")
    elsif search == "forward_match"
      User.where("name LIKE ?","#{word}%")
    elsif search == "backward_match"
     User.where("name LIKE ","%#{word}")
    elsif search == "partial_match"
      User.where("name LIKE ?","%#{word}%")
    else
      User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @recruitments = @user.recruitments
    @recruitment = Recruitment.new
  end

  def index
    @users = User.where(is_withdrawal: false)
    @recruitment = Recruitment.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      tags = Vision.get_image_data(params[:user][:profile_image])
      @user.tags.destroy_all
      tags.each do |tag|
        @user.tags.create(name: tag)
      end
      redirect_to user_path(@user), notice: "更新できました。"
    else
      render "edit"
    end
  end

  def withdrawal
    @user = User.find(params[:user_id])
    @user.update(is_withdrawal: true)
    # reset_session
    sign_out @user unless current_user.is_admin?
    flash[:notice] = "退会完了いたしました。"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>アイコン</th>
      <th>ユーザー名</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <!--<td>-->
        <!--  <div class="tag-box">-->
        <!--  <% user.tags.each do |tag| %>-->
        <!--    <span class="label"><%= tag.name %></span>-->
        <!--  <% end %>-->
        <!--  </div>-->
        <!--</td>-->
        <td><span class="font-small"><%= link_to user.name, user %></span></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td id="relationships-btn-<%= user.id %>">
          <%= render "relationships/btn", user: user %>
        </td>
        <td><%= link_to '詳細ページ', user, class: "user_#{user.id} btn btn-success pull-right btn-sm" %></td>
        <% if current_user.is_admin? && !user.is_admin && !user.is_guest? %>
          <td><%= link_to '退会ボタン', withdrawal_path(user.id), method: :post, class: "user_#{user.id} btn btn-danger pull-right btn-sm", data: { confirm: "&#8203;``【oaicite:0】``&#8203;アカウントを削除してもよろしいですか？" } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr>
    <%= image_tag user.get_profile_image, size: '150x150' %>
  </tr>
  <tr>
    <th></th>
    <td>
      <div class="tag-box">
        <% user.tags.each do |tag| %>
          <span class="label" style="font-size:0.72em;background-color:lightGray;display:inline-block;border-radius:3px;padding:4px 8px;"><%= tag.name %></span>
        <% end %>
      </div>
    </td>
  </tr>
  <tr>
    <th>ユーザー名</th>
    <td><%= user.name %></td>
  </tr>
  <tr>
    <th>自己紹介文</th>
    <td><%= user.introduction %></td>
  </tr>
  <tr>
    <th>フォローの数</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>フォロワーの数</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <td><%= render "relationships/btn", user: user %></td>
  <% else %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>ユーザー編集画面</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :ユーザー名 %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :アイコン %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :自己紹介文 %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
        <%= link_to '退会ボタン', withdrawal_path(current_user), method: :post,  class: "btn btn-danger pull-right", data: { confirm: "【確認】アカウントを削除してもよろしいですか？" } %>
      </div>

    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー詳細ページ</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">新規募集</h2>
      <%= render 'recruitments/form', recruitment: @recruitment %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>ユーザー一覧</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>ユーザー詳細ページ</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">新規募集</h2>
      <%= render 'recruitments/form', recruitment: @recruitment %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>募集一覧</h2>
      <%= render 'recruitments/index',recruitments: @recruitments %>
    </div>
  </div>
</div>