config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :recruitments, only: [:new, :index, :show, :create, :edit, :destroy, :update] do
    resources :recruitment_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
     resource :relationships, only: [:create, :destroy]
     get 'followings' => 'relationships#followings', as: 'followings'
     get 'followers' => 'relationships#followers', as: 'followers'
  end
  post 'users/withdrawal/:user_id', to: 'users#withdrawal', as: 'withdrawal'
  root "homes#top"
  get "home/about"=>"homes#about"
  get '/homes/guest_login', to: 'homes#guest_login'
  get "search" => "searches#search"

 # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recruitment
  validates_uniqueness_of :recruitment_id, scope: :user_id
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord
  belongs_to :user
	has_many :recruitment_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      Recruitment.where("title LIKE ?","#{word}")
    elsif search == "forward_match"
      Recruitment.where("title LIKE ?","#{word}%")
    elsif search == "backward_match"
      Recruitment.where("title LIKE ?","%#{word}")
    elsif search == "partial_match"
      Recruitment.where("title LIKE ?","%#{word}%")
    else
      Recruitment.all
    end
  end

end

app/models/recruitment_comment.rb
class RecruitmentComment < ApplicationRecord
    belongs_to :user
    belongs_to :recruitment
    
    validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :user_tags
  has_many :users, through: :user_tags

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recruitments
  has_many :recruitment_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :user_tags
  has_many :tags, through: :user_tags

  # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  #validates :introduction, length: { maximum: 50 }


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.png'
  end

  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def is_guest?
    email == "guest@example.com"
  end

  def active_for_authentication? # アカウント凍結のログイン分岐
    super && (is_withdrawal == false)
  end

  def inactive_message # アカウント凍結時のエラーメッセージ
    !is_withdrawal ? super : :locked
  end

  def self.looks(search, word)
    if search == "perfect_match"
       User.where("name LIKE ?", "#{word}")
    elsif search == "forward_match"
      User.where("name LIKE ?","#{word}%")
    elsif search == "backward_match"
     User.where("name LIKE ","%#{word}")
    elsif search == "partial_match"
      User.where("name LIKE ?","%#{word}%")
    else
      User.all
    end
  end
end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
    @recruitment = Recruitment.find(params[:recruitment_id])
    favorite = current_user.favorites.new(recruitment_id: @recruitment.id)
    favorite.save
    end

  def destroy
    @recruitment = Recruitment.find(params[:recruitment_id])
    favorite = current_user.favorites.find_by(recruitment_id: @recruitment.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def guest_login
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
      user.name = "ゲストユーザー"
    end
    sign_in user
    redirect_to user_path(user), notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params["range"]

    if @range == "ユーザー"
      @users = User.looks(params["search"], params["word"])
    else
      @recruitments = Recruitment.looks(params["search"], params["word"])
    end
  end
end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @recruitments = @user.recruitments
    @recruitment = Recruitment.new
  end

  def index
    @users = User.where(is_withdrawal: false)
    @recruitment = Recruitment.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      tags = Vision.get_image_data(params[:user][:profile_image])
      @user.tags.destroy_all
      tags.each do |tag|
        @user.tags.create(name: tag)
      end
      redirect_to user_path(@user), notice: "更新できました。"
    else
      render "edit"
    end
  end

  def withdrawal
    @user = User.find(params[:user_id])
    @user.update(is_withdrawal: true)
    # reset_session
    sign_out @user unless current_user.is_admin?
    flash[:notice] = "退会完了いたしました。"
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <p class="alert alert-warning"><%= notice %></p>
<% elsif flash[:alert] %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Gathering of Adventurers.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header style="background-color: #FF8C00">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <a class="navbar-brand text-light" href="/"><%= image_tag("logo.png", width: "231px", height: "65px") %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li>
            <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> マイページ
            <% end %>
          </li>
          <li>
            <%=  link_to users_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> ユーザー一覧
            <% end %>
          </li>
          <li>
            <%=  link_to recruitments_path ,class: 'nav-link text-light' do %>
              <i class="fa-regular fa-face-smile"></i> 募集ページ
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> マイページ
            <% end %>
          </li>
          <li>
            <%= link_to home_about_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> アバウトページ
            <% end %>
          </li>
          <li>
            <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form d-flex justify-content-center mt-3">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <div>
        <%= f.select :range, options_for_select([['ユーザー'], ['募集']]) %>
        <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"], ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      </div>
      <div class="row">
        <div>
          <%= f.text_field :word, class: "form-control" %>
        </div>
        <div>
          <%= button_tag type: "submit", class: "btn btn-light" do %>
            <i class="fa-solid fa-magnifying-glass" style="color: #FF8C00;"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gathering of Adventurers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/374d174b51.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <main>
      <%= render 'layouts/flash' %>
      <%= render 'layouts/search' %>
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>